### PR TITLE
Basic profile retrieval by Username or UUID

### PR DESCRIPTION
**Pull request by hmehta9744**

### CODE REVIEW

**Comment by endercrest** [comment]
@hmehta9744 Before I merge this and take a full look, would you be able to add documentation to the main README.

**Comment by hmehta9744** [comment]
@endercrest README updated

**Comment by endercrest** [comment]
@hmehta9744 One more small problem, You accidentally committed and .idea file. Once that is fixed, I will gladly merge the PR. :)

**Comment by hmehta9744** [comment]
@endercrest Oops, guess I should go to sleep now. Reverted .idea from commit.

**Comment by endercrest** [comment]
@hmehta9744 Thanks for the PR.

**Pull request merged**
